import type { PermissionMode } from '../../../shared/protocol';
import {
  addPermission,
  beginPermissionReconciliation,
  draftPermissionMode,
  finishPermissionReconciliation,
  getPermissionGroupMembers,
  getPermissionModeForSession,
  getPermissionReconciliationMetadataSize,
  getPermissionSignature,
  groupPermissions,
  removePermission,
  removePermissionModeForSession,
  removeQuestion,
  reconcilePermissions,
  resetDraftPermissionMode,
  saveProjectPermissionMode,
  setPermissionAutoApprovePresentation,
  setDefaultPermissionModePreference,
  setDraftPermissionMode,
  setPermissionModeForSession,
  setQuestions,
  syncDraftPermissionForWorkspace,
  syncSessionPermissionModesToHost,
  upsertQuestion,
} from '../state';

export const permissionsStore = {
  draftPermissionMode,
  setDraftPermissionMode,
  getPermissionModeForSession,
  setPermissionModeForSession,
  removePermissionModeForSession,
  resetDraftPermissionMode,
  syncDraftPermissionForWorkspace,
  syncSessionPermissionModesToHost,
  saveProjectPermissionMode,
  setDefaultPermissionModePreference,
  getPermissionGroupMembers,
  getPermissionSignature,
  groupPermissions,
  setQuestions,
  upsertQuestion,
  removeQuestion,
  addPermission,
  setPermissionAutoApprovePresentation,
  removePermission,
  beginPermissionReconciliation,
  finishPermissionReconciliation,
  reconcilePermissions,
  getPermissionReconciliationMetadataSize,
};

export type PermissionsStore = typeof permissionsStore;
export type PermissionModeValue = PermissionMode;
