import { defineConfig } from 'oxlint';

export default defineConfig({
  ignorePatterns: ['assets/**', 'dist/**', '*.vsix'],
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'react', 'import'],
  jsPlugins: [
    {
      name: 'anti-slop',
      specifier: './node_modules/oxlint-plugin-anti-slop/dist/index.mjs',
    },
  ],
  options: {
    reportUnusedDisableDirectives: 'error',
  },
  categories: {
    correctness: 'error',
    suspicious: 'warn',
  },
  rules: {
    'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
    'eslint/no-control-regex': 'error',
    'eslint/no-underscore-dangle': [
      'warn',
      {
        allow: [
          '__initialTheme',
          '__initialWebviewState',
          '__VARRO_VERSION__',
          '__parseMarkdownForTests',
          '__resetMarkdownCachesForTests',
          '__sendToExtension',
          '__varroE2E',
          '__varroPasteText',
          '__vscodeWebviewState',
          '_context',
          '_disposeGeneration',
          '_lastContextSnapshot',
          '_lastDiagnosticsSourceKey',
          '_lastEmittedContextSnapshot',
          '_managedProcess',
          '_phase',
          '_port',
          '_process',
          '_processErrorHandler',
          '_processExitHandler',
          '_processStderrHandler',
          '_processStdoutHandler',
          '_restartTimer',
          '_startAttemptId',
          '_startPromise',
          '_status',
          '_terminalSelection',
        ],
      },
    ],
    'eslint/no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_',
        ignoreRestSiblings: true,
        varsIgnorePattern: '^_',
      },
    ],
    'eslint/no-useless-assignment': 'off',
    'eslint/no-console': 'warn',
    'eslint/no-debugger': 'error',
    'eslint/no-var': 'error',
    'eslint/prefer-const': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-namespace': 'error',
    'typescript/consistent-type-imports': 'warn',
    // Type-aware (requires --type-aware): unhandled async failures are invisible in both hosts.
    'typescript/no-floating-promises': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/await-thenable': 'error',
    // Other type-aware rules in the enabled categories are not adopted yet.
    'typescript/consistent-return': 'off',
    'typescript/no-base-to-string': 'off',
    'typescript/no-implied-eval': 'off',
    'typescript/no-meaningless-void-operator': 'off',
    'typescript/no-misused-spread': 'off',
    'typescript/no-redundant-type-constituents': 'off',
    'typescript/no-unnecessary-boolean-literal-compare': 'off',
    'typescript/no-unnecessary-template-expression': 'off',
    'typescript/no-unnecessary-type-arguments': 'off',
    'typescript/no-unnecessary-type-assertion': 'off',
    'typescript/no-unnecessary-type-conversion': 'off',
    'typescript/no-unnecessary-type-parameters': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/require-array-sort-compare': 'off',
    'typescript/restrict-template-expressions': 'off',
    'typescript/unbound-method': 'off',
    'import/no-duplicates': 'error',
    // Keep lifecycle handlers and test helpers beside their registration and cleanup.
    'unicorn/consistent-function-scoping': 'off',
    'react/immutability': 'off',
    'react/purity': 'off',
    'react/refs': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/jsx-key': 'off',
    'react/jsx-no-duplicate-props': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
  },
  overrides: [
    {
      // Async mock implementations and fixture servers are intentional in tests.
      files: ['**/*.test.ts', '**/*.test.tsx', '**/*.test-support.ts', '**/*.test-utils.ts'],
      rules: { 'typescript/no-misused-promises': 'off' },
    },
  ],
});
