import { defineConfig } from 'oxlint';

export default defineConfig({
  ignorePatterns: ['assets/**', 'dist/**', '*.vsix'],
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'react', 'import'],
  jsPlugins: [
    { name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' },
  ],
  options: {
    reportUnusedDisableDirectives: 'error',
  },
  categories: {
    correctness: 'error',
    suspicious: 'warn',
  },
  rules: {
    'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
    'eslint/no-control-regex': 'error',
    'eslint/no-underscore-dangle': [
      'warn',
      {
        allow: [
          '__initialTheme',
          '__initialWebviewState',
          '__parseMarkdownForTests',
          '__resetMarkdownCachesForTests',
          '__sendToExtension',
          '__varroE2E',
          '__varroPasteText',
          '__vscodeWebviewState',
          '_context',
          '_disposeGeneration',
          '_lastContextSnapshot',
          '_lastDiagnosticsSourceKey',
          '_lastEmittedContextSnapshot',
          '_managedProcess',
          '_phase',
          '_port',
          '_process',
          '_processErrorHandler',
          '_processExitHandler',
          '_processStderrHandler',
          '_processStdoutHandler',
          '_restartTimer',
          '_startAttemptId',
          '_startPromise',
          '_status',
          '_terminalSelection',
        ],
      },
    ],
    'eslint/no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_',
        ignoreRestSiblings: true,
        varsIgnorePattern: '^_',
      },
    ],
    'eslint/no-useless-assignment': 'off',
    'eslint/no-console': 'warn',
    'eslint/no-debugger': 'error',
    'eslint/no-var': 'error',
    'eslint/prefer-const': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-namespace': 'error',
    'typescript/consistent-type-imports': 'warn',
    'import/no-duplicates': 'error',
    'react/immutability': 'off',
    'react/purity': 'off',
    'react/refs': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/jsx-key': 'off',
    'react/jsx-no-duplicate-props': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
  },
});
