import { runInNewContext } from 'node:vm';
import { describe, expect, it, vi } from 'vitest';
import { renderAboutHtml } from './about-view';
import type { AboutViewData } from './about-view';

const data: AboutViewData = {
  name: 'Varro',
  description: 'OpenCode workbench',
  logoUri: 'webview:/icon.png',
  varroVersion: '0.31.0',
  cliVersion: '1.18.4',
  installMethod: 'bun',
  installedOn: 'Oct 1, 2026, 9:45:12 AM',
  binary: '/bin/opencode',
  serverVersion: '1.18.4',
  serverUrl: 'http://localhost:4096',
  ownership: 'Managed by Varro',
  serverStatus: 'Running',
  healthy: true,
  activeAgents: '0',
  serverStartedOn: 'Oct 1, 2026, 10:00:00 AM',
  vscodeClients: '1',
  otherClients: '0',
  autoUpdate: true,
  vscodeVersion: '1.120.0',
  nodeVersion: 'v24.15.0',
  platform: 'darwin arm64',
};

function openPage(hiddenInitially = false) {
  const page = document.implementation.createHTMLDocument();
  page.documentElement.innerHTML = renderAboutHtml(data, 'vscode-webview-resource:');
  const events = new window.EventTarget();
  let hidden = hiddenInitially;
  Object.defineProperty(page, 'hidden', { get: () => hidden });
  const postMessage = vi.fn();
  const setInterval = vi.fn((_callback: () => void, _delay: number) => 1);
  const clearInterval = vi.fn();
  // Execute only the script generated by our About renderer with isolated page APIs.
  runInNewContext(page.querySelector('script')!.textContent!, {
    document: page,
    window: events,
    acquireVsCodeApi: () => ({ postMessage }),
    setInterval,
    clearInterval,
  });
  return {
    page,
    events,
    postMessage,
    setInterval,
    clearInterval,
    setHidden(value: boolean) {
      hidden = value;
      page.dispatchEvent(new Event('visibilitychange'));
    },
  };
}

describe('About page', () => {
  it.each(['0', 'Unknown', '1', '2'])(
    'shows the other clients row initially only for a positive count: %s',
    (otherClients) => {
      const root = document.createElement('div');
      root.innerHTML = renderAboutHtml({ ...data, otherClients }, 'vscode-webview-resource:');
      const row = root.querySelectorAll<HTMLElement>('[data-other-clients]');
      expect(row).toHaveLength(2);
      for (const element of row) expect(element.hidden).toBe(!(Number(otherClients) > 0));
    }
  );

  it('refreshes on opening and every five seconds only while visible', () => {
    const view = openPage();
    expect(view.postMessage).toHaveBeenCalledExactlyOnceWith({ action: 'refresh' });
    expect(view.setInterval).toHaveBeenCalledWith(expect.any(Function), 5000);
    const poll = view.setInterval.mock.calls[0]![0];
    poll();
    expect(view.postMessage).toHaveBeenCalledTimes(2);

    view.setHidden(true);
    expect(view.clearInterval).toHaveBeenLastCalledWith(1);
    poll();
    expect(view.postMessage).toHaveBeenCalledTimes(2);
    view.setHidden(false);
    expect(view.postMessage).toHaveBeenCalledTimes(3);
    expect(view.setInterval).toHaveBeenCalledTimes(2);
    view.events.dispatchEvent(new Event('pagehide'));
    expect(view.clearInterval).toHaveBeenLastCalledWith(1);
  });

  it('does not start polling until a hidden page becomes visible', () => {
    const view = openPage(true);
    expect(view.postMessage).not.toHaveBeenCalled();
    expect(view.setInterval).not.toHaveBeenCalled();
    view.setHidden(false);
    expect(view.postMessage).toHaveBeenCalledExactlyOnceWith({ action: 'refresh' });
    expect(view.setInterval).toHaveBeenCalledOnce();
  });

  it('updates live fields in place and preserves diagnostic feedback', () => {
    const view = openPage();
    const otherClientsRow = view.page.querySelectorAll<HTMLElement>('[data-other-clients]');
    for (const element of otherClientsRow) expect(element.hidden).toBe(true);
    expect(
      view.page.querySelector('[data-about-field="activeAgents"]')?.previousElementSibling
        ?.textContent
    ).toBe('Active sessions');
    const copyButton = view.page.getElementById('copy-diagnostics')!;
    copyButton.click();
    expect(view.postMessage).toHaveBeenLastCalledWith({
      action: 'copyDiagnostics',
      includePaths: false,
    });
    view.events.dispatchEvent(
      new MessageEvent('message', {
        data: { type: 'diagnostics-result', text: 'Copied' },
      })
    );
    const update = (updated: AboutViewData) => {
      view.events.dispatchEvent(
        new MessageEvent('message', {
          data: { type: 'about-update', data: updated },
        })
      );
    };
    update({
      ...data,
      healthy: false,
      serverStatus: 'Error: disconnected',
      cliVersion: '1.18.9',
      installMethod: 'npm',
      installedOn: 'Oct 2, 2026, 11:10:23 AM',
      binary: '/new/opencode',
      serverVersion: 'Unknown',
      serverUrl: 'http://localhost:5096',
      ownership: 'Unmanaged',
      activeAgents: '2',
      serverStartedOn: 'Oct 2, 2026, 11:00:00 AM',
      vscodeClients: '3',
      otherClients: '2',
      autoUpdate: false,
      updateNotice: '<img src=x onerror=alert(1)>',
    });
    const field = (name: string) =>
      view.page.querySelector(`[data-about-field="${name}"]`)!.textContent;
    expect(field('statusLabel')).toBe('Needs attention');
    expect(field('serverStatus')).toBe('Error: disconnected');
    expect(field('cliVersion')).toBe('1.18.9');
    expect(field('installMethod')).toBe('npm');
    expect(field('installedOn')).toBe('Oct 2, 2026, 11:10:23 AM');
    expect(field('binary')).toBe('/new/opencode');
    expect(field('serverVersion')).toBe('Unknown');
    expect(field('serverUrl')).toBe('http://localhost:5096');
    expect(field('ownership')).toBe('Unmanaged');
    expect(field('activeAgents')).toBe('2');
    expect(field('serverStartedOn')).toBe('Oct 2, 2026, 11:00:00 AM');
    expect(field('vscodeClients')).toBe('3');
    expect(field('otherClients')).toBe('2');
    for (const element of otherClientsRow) expect(element.hidden).toBe(false);
    expect(field('autoUpdate')).toBe('Disabled');
    expect(view.page.getElementById('server-status')!.classList.contains('unhealthy')).toBe(true);
    expect(view.page.getElementById('server-status')!.classList.contains('healthy')).toBe(false);
    expect(view.page.getElementById('update-notice')!.hidden).toBe(false);
    expect(view.page.querySelector('#update-notice img')).toBeNull();
    expect(field('updateNotice')).toBe('<img src=x onerror=alert(1)>');
    expect(view.page.getElementById('copy-diagnostics')).toBe(copyButton);
    expect(view.page.getElementById('diagnostics-result')!.textContent).toBe('Copied');

    update(data);
    expect(view.page.getElementById('update-notice')!.hidden).toBe(true);
    expect(view.page.getElementById('server-status')!.classList.contains('healthy')).toBe(true);
    expect(field('statusLabel')).toBe('System ready');
    expect(field('autoUpdate')).toBe('Enabled');
    expect(field('installedOn')).toBe('Oct 1, 2026, 9:45:12 AM');
    for (const element of otherClientsRow) expect(element.hidden).toBe(true);
    update({ ...data, otherClients: 'Unknown' });
    for (const element of otherClientsRow) expect(element.hidden).toBe(true);
    update({ ...data, otherClients: '1' });
    for (const element of otherClientsRow) expect(element.hidden).toBe(false);
  });
});
